name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: krishana7911
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Updated Contribution Snake animation" || echo "No changes to commit"
          git push
